# Generated by Django 5.0.6 on 2024-05-20 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('publisher', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
